CREATE TABLE IF NOT EXISTS user_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    action VARCHAR(10) NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL

    CONSTRAINT positive_user_id CHECK (user_id > 0),
    CONSTRAINT positive_event_id CHECK (event_id > 0),
    UNIQUE (user_id, event_id),
    CONSTRAINT action_not_blank CHECK (TRIM(action) <> '')
);

CREATE TABLE IF NOT EXISTS event_similarity (
    eventA BIGINT NOT NULL,
    eventB BIGINT NOT NULL,
    score DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT event_similarity_pk PRIMARY KEY (eventA, eventB),
    CONSTRAINT unique_event_pair UNIQUE (eventA, eventB)
);

CREATE INDEX IF NOT EXISTS idx_event_action ON user_actions(event_id);