services:
  stats-server:
    build: stat/stat-server
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=statsuser
      - SPRING_DATASOURCE_PASSWORD=statspass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=statsuser
      - POSTGRES_PASSWORD=statspass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U statsuser -d stats" ]
      interval: 10s
      timeout: 5s
      retries: 5

  ewm-service:
    build: main-service
    image: ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
      - SPRING_DATASOURCE_USERNAME=ewmuser
      - SPRING_DATASOURCE_PASSWORD=ewmpass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - STATS_SERVER_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    container_name: ewm-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewmuser
      - POSTGRES_PASSWORD=ewmpass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ewmuser -d ewm" ]
      interval: 10s
      timeout: 5s
      retries: 5