CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,

    CONSTRAINT user_name_not_blank CHECK (TRIM(name) <> ''),
    CONSTRAINT email_not_blank CHECK (TRIM(email) <> ''),
    CONSTRAINT email_has_no_whitespace CHECK (email NOT LIKE '% %')
);