server:
  port: 0

spring:
  datasource:
    driverClassName: 'org.h2.Driver'
    url: 'jdbc:h2:mem:events_db'
    username: 'ewmuser'
    password: 'ewmpass'
  jpa:
    show_sql: true
    hibernate.ddl-auto: none
    properties.hibernate:
      dialect: 'org.hibernate.dialect.H2Dialect'
      jdbc.time_zone: UTC
      format_sql: true
  sql.init.mode: always

# Stats-server custom properties
stats-server:
  id: 'stats-server'
  retryBackOffPeriod: 10000
  retryMaxAttempts: 5

logging:
  level:
    root: INFO
    org.springframework:
      orm.jpa:
        JpaTransactionManager: DEBUG
      transaction:
        interceptor: DEBUG
    ru.practicum.core.event: DEBUG