server.port=9090
#client.url=http://localhost:9090
# H2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:stats
spring.datasource.username=statsuser
spring.datasource.password=statspass
# Logging levels
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO
logging.level.org.springframework.transaction.interceptor=DEBUG
logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
logging.level.ru.practicum=DEBUG
# JPA
spring.jpa.show_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
## Profile
## Profile
##spring.profiles.active=test
## SQL
#spring.sql.init.mode=always
## Logging levels
#logging.level.org.springframework.orm.jpa=INFO
#logging.level.org.springframework.transaction=INFO
#logging.level.org.springframework.transaction.interceptor=DEBUG
#logging.level.org.springframework.orm.jpa.JpaTransactionManager=DEBUG
#logging.level.ru.practicum.shareit=DEBUG
## JPA
#spring.jpa.show_sql=true
#spring.jpa.properties.hibernate.jdbc.time_zone=UTC
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect